### ISSUE TITLE
Race condition in FillerManager.cs GetFiller(PropertyInfo propertyInfo)

### ISSUE THREAD

**Issue by sandimschuh** [MisterJames/GenFu#132]
When executing in parallel (unit testing) I get following Exception:

Result StackTrace:	
----- Inner Stack Trace #1 (System.ArgumentException) -----
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at GenFu.FillerManager.GetFiller(PropertyInfo propertyInfo) in C:\james\code\GenFu\src\GenFu\FillerManager.cs:line 165
   at GenFu.GenFu.SetPropertyValue(Object instance, PropertyInfo property) in C:\james\code\GenFu\src\GenFu\GenFu.cs:line 111
   at GenFu.GenFu.New(Object instance) in C:\james\code\GenFu\src\GenFu\GenFu.cs:line 53
   at GenFu.GenFu.BuildList(Type type, Int32 itemCount) in C:\james\code\GenFu\src\GenFu\GenFu.cs:line 101
   at GenFu.GenFu.ListOf[T](Int32 itemCount) in C:\james\code\GenFu\src\GenFu\GenFu.cs:line 89
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
Result Message:	
System.AggregateException : One or more errors occurred. (An item with the same key has already been added. Key: System.Nullable`1[System.Int64])
---- System.ArgumentException : An item with the same key has already been added. Key: System.Nullable`1[System.Int64]

**Comment by sandimschuh** [comment]
Fixed this temporarily on my site by wrapping entire body of GetFilter() into a lock(){...} block.

**Comment by dpaquette** [comment]
We used to get this on the GenFu unit tests. Our workaround for the time being was to disable parallel tests

**Comment by marcoregueira** [comment]
Please check https://github.com/MisterJames/GenFu/pull/133.

**Comment by marcoregueira** [comment]
Hi @dpaquette. I've got some tests failing randomly because of the problem listed in this issue.  I'd rather prefer not disabling the parallel tests. Running them in parallel increases my confidence in the whole system and is more performant. 

The provided PR #133 solves this issue and is more performant than just a lock because it uses reader and writer locks. Had you the opportunity to check it out?
